version: '2.29.6'

services:
  secondary1:
    environment:
      - GRPC_PORT=9090
      - SLEEP_IN_MILLIS=15000

    container_name: secondary1
    image: ogavrylenko/replicated-log-secondary:v1
    build:
      context: .
      dockerfile: Dockerfile-secondary
    ports:
      - 8081:8081
    networks:
      - backend-net

  secondary2:
    environment:
      - GRPC_PORT=9090
      - SLEEP_IN_MILLIS=0

    container_name: secondary2
    image: ogavrylenko/replicated-log-secondary:v1
    ports:
      - 8082:8081
    networks:
      - backend-net
    depends_on:
      - secondary1

  master:
    environment:
      - SEC1_HOST=secondary1
      - SEC1_PORT=9090
      - SEC2_HOST=secondary2
      - SEC2_PORT=9090
      - REPLICAS_NUM=2
    image: ogavrylenko/replicated-log-master:v1
    container_name: master
    build:
      context: .
      dockerfile: Dockerfile-master
    ports:
      - 8080:8080
    networks:
      - backend-net
    depends_on:
      - secondary1
      - secondary2

networks:
  backend-net:
    name: backend-net
    driver: bridge