#version: '3.x'

services:
  secondary1:
    environment:
      - GRPC_PORT=9090
      - SLEEP_IN_MILLIS=100

    container_name: secondary1
    image: ogavrylenko/replicated-log-secondary:v3
    build:
      context: .
      dockerfile: Dockerfile-secondary
    ports:
      - 8081:8081
    networks:
      backend-net:
        ipv4_address: 172.19.0.4

  secondary2:
    environment:
      - GRPC_PORT=9090
      - SLEEP_IN_MILLIS=150

    container_name: secondary2
    image: ogavrylenko/replicated-log-secondary:v3
    ports:
      - 8082:8081
    networks:
      backend-net:
        ipv4_address: 172.19.0.5
    depends_on:
      - secondary1

  master:
    environment:
      - SEC1_HOST=172.19.0.4
      - SEC1_PORT=9090
      - SEC2_HOST=172.19.0.5
      - SEC2_PORT=9090
    image: ogavrylenko/replicated-log-master:v3
    container_name: master
    build:
      context: .
      dockerfile: Dockerfile-master
    ports:
      - 8080:8080
    networks:
      backend-net:
        ipv4_address: 172.19.0.3
    depends_on:
      - secondary1
      - secondary2

networks:
  backend-net:
    name: backend-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1