spring:
  application:
    name: master
client:
  sec1:
    host: ${SEC1_HOST:secondary1}
    port: ${SEC1_PORT:9090}
  sec2:
    host: ${SEC2_HOST:secondary2}
    port: ${SEC2_PORT:9090}
logging:
  file:
    name: /var/log/master.log
  pattern:
    dateformat: "[%d{HH:mm:ss.SSS}]"
  level:
    com.distributed.master: info
    io.grpc: info
    io.netty: info
  include-application-name: false