client:
  secNumber: ${SEC_NUM:2}
  sec1:
    host: ${SEC1_HOST:secondary1}
    port: ${SEC1_PORT:9090}
  sec2:
    host: ${SEC2_HOST:secondary2}
    port: ${SEC2_PORT:9090}
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
  level:
    com.distributed.master: info
  include-application-name: false