spring:
  application:
    name: secondarynode
server:
  port: ${PORT:8081}
grpc:
  server:
    port: ${GRPC_PORT:9090}
    sleepInMillis: ${SLEEP_IN_MILLIS:0}
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
  level:
    com.distributed.master: info
  include-application-name: false

