spring:
  application:
    name: secondary
server:
  port: ${PORT:8081}
grpc:
  server:
    port: ${GRPC_PORT:9090}
    sleepInMillis: ${SLEEP_IN_MILLIS:0}
logging:
  file:
    name: /var/log/secondary.log
  pattern:
    dateformat: "%d{HH:mm:ss.SSS}"
  level:
    com.distributed.master: info
    io.grpc: info
    io.netty: info
  include-application-name: false

